---
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
        - name: calico-node
          env:
            - name: FELIX_PROMETHEUSMETRICSENABLED
              value: "true"
            - name: FELIX_PROMETHEUSMETRICSPORT
              value: "9091"
            - name: FELIX_IGNORELOOSERPF
              value: "true"
            # We assign IP on br-ex interface while testing the deployed Openstack cluster and
            # we need Calico to skip this interface while discovering the
            # network changes on the host to prevent announcing unnecessary networks.
            - name: IP_AUTODETECTION_METHOD
              value: "skip-interface=br-ex"
...
